version: '3'

services:
  nginx:
    init: true
    build:
      context: requirements/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    init: true
    build:
      context: requirements/wordpress
    container_name: wordpress
    expose:
      - "9000:9000"
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: always

  mariadb:
    init: true
    build:
      context: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/Users/acouture/Desktop/wordpress_data'
  mariadb_data:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/Users/acouture/Desktop/mariadb_data'


networks:
  inception:
    driver: bridge
